### ISSUE TITLE
Where is a reference for the instruction set of the cpu?

### ISSUE THREAD

**Issue by laura240406** [LBPHacker/CasioEmu#20]

**Comment by LBPHacker** [comment]
So this entire repo is a sort of side effect of what transpired in [this thread](https://community.casiocalc.org/topic/7583-fx-82-83gt-115-991es-plus-hacking) over on the casiocalc forum. Two users there, SopaXorzTaker and user202729, discovered most of the datasheets, manuals and inner workings of the only model this repo implements, and it might be best to consult that thread or ask them for reference material in general. The instruction set is a bit of an exception because I happen to have the reference I followed while implementing the CPU still. While I'm not comfortable with the idea of uploading it here, I guess I can mail it to you, see my profile.

**Comment by laura240406** [comment]
Thank you :)
